version: '3.0'
services:
  # 服务名
  resource-pool-front:
    # 指定构建镜像Dockerfile所在文件夹的路径
    build: .
    # 镜像名
    image: resource-pool-front
    # 设置容器开机启动和自动重启
    restart: always
    # 容器名
    container_name: resource-pool-front
    # 将宿主机的80端口映射到容器内的服务端口
    ports:
      - 80:80
